# Generated by Django 2.2.7 on 2019-11-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191114_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
