# Generated by Django 2.2.7 on 2019-11-16 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
